image: node:16.20.1-slim@sha256:f9b352a2b524dd1c56c65e0cb365f7517093a7d3298f41a8e85dd034a6f33474

before_script:
  - echo ':before_script'
  - cat /etc/os-release
  - npm --version
  - node --version
  - npm install
  - echo 'end :before_script'

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - quality-check

lint:
  stage: quality-check
  script:
    - npm run markdown:lint:linux
